### Test Endpoint
GET https://mynodejsproject4.vercel.app/test

### Get All Users
GET https://mynodejsproject4.vercel.app/users

### Create New User - Bob
POST https://mynodejsproject4.vercel.app/users
Content-Type: application/json

{
  "name": "rakshitha",
  "age": 35
}


### Update User by ID (Replace with actual MongoDB ObjectId)
PUT https://mynodejsproject4.vercel.app/users/1
Content-Type: application/json

{ "id": 1,
  "name": "Updated Bob",
  "age": 40
}

### Delete User by ID (Replace with actual MongoDB ObjectId)
DELETE https://mynodejsproject4.vercel.app/users/2

### Search Users - Case insensitive
GET https://mynodejsproject4.vercel.app/search?name=John


### Get Single User by ID (Replace with actual MongoDB ObjectId)
GET https://mynodejsproject4.vercel.app/users/1
